USE CarDealership
GO

IF EXISTS(
	SELECT *
	FROM sys.tables
	WHERE name='Vehicle')
DROP Table Vehicle
GO

IF EXISTS(
	SELECT *
	FROM sys.tables
	WHERE name='Sale')
DROP TABLE Sale
GO

IF EXISTS(
	SELECT *
	FROM sys.tables
	WHERE name='Special')
DROP TABLE Special
GO

IF EXISTS(
	SELECT *
	FROM sys.tables
	WHERE name='[Roles]')
DROP TABLE [Roles]
GO

CREATE TABLE Vehicle(
VehicleId INT PRIMARY KEY IDENTITY(1,1),
Make VARCHAR(30) NOT NULL,
Model VARCHAR(30) NOT NULL,
[Year] INT NOT NULL,
[Image] VARCHAR(100),
BodyStyle VARCHAR(30) NOT NULL,
Trans VARCHAR(15) NOT NULL,
Color VARCHAR(25) NOT NULL,
Interior VARCHAR(30) NOT NULL,
Mileage INT,
VinNumber VARCHAR(30) NOT NULL,
SalePrice DECIMAL NOT NULL,
MSRP DECIMAL NOT NULL,
[Description] VARCHAR(MAX) NOT NULL,
IsFeatured TINYINT NOT NULL,
InStock TINYINT NOT NULL
)
GO

CREATE TABLE Sale(
Id INT PRIMARY KEY IDENTITY (1,1),
VehicleId INT FOREIGN KEY REFERENCES Vehicle(VehicleId),
Name VARCHAR(50) NOT NULL,
Phone VARCHAR(10) NOT NULL,
Email VARCHAR(50) NOT NULL,
Street1 VARCHAR(50) NOT NULL,
Street2 VARCHAR(50),
City VARCHAR(30) NOT NULL,
[State] VARCHAR(20) NOT NULL,
Zipcode VARCHAR(5) NOT NULL,
PurchasePrice DECIMAL NOT NULL,
PurchaseType VARCHAR(20) NOT NULL
)
GO

CREATE TABLE Special(
Id INT PRIMARY KEY IDENTITY (1,1),
VehicleId INT FOREIGN KEY REFERENCES Vehicle(VehicleId),
Title VARCHAR(100),
Details VARCHAR(MAX)
)
GO

CREATE TABLE [Role](
RoleId INT PRIMARY KEY IDENTITY(1,1),
RoleName VARCHAR(30) NOT NULL
)
GO

